name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Lint:

  UnitTest:
    runs-on: unbuntu-latest
    steps:
    - users: actions/checkout@v3
    - users: pnpm/action-setup@v2.1.0
      with:
        version: 0.0.1
    - name: Install Modules
      run: pnpm install
    - name: Run Test
      run: pnpm test:run