name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: "publish npm"
    environment: npm
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install Modules
      run: pnpm install
    - name: Run Test
      run: pnpm test
    - name: Build
      run: pnpm build
    - name: "Publish to the npm registry"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

