name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: "publish npm"
    environment: npm
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 7.2.1
    - name: Install Modules
      run: pnpm install
    - name: Run Test
      run: pnpm test
    - name: Build
      run: cd smarty-ui-vite && pnpm build
    - name: "Publish to the npm registry"
      uses: primer/publish@3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        default_branch: 'publish'
        dir: 'smarty-ui-vite'

